MODEL:
  BACKBONE: 'cs3darknet_l'   # convnext_base_in22ft1k
  PRETRAINED: True
  ACT_LAYER: 'silu'   # cspnet does not support norm_layer and act_layer
  NORM_LAYER: 'bn'    # bn is not compatible with convnext
  POOLING: False
  EMBEDDING_DIM: 512
  LOSS: 'partial_fc'
  NUM_CLASS: 360232
  SAMPLE_RATE: 0.2

DATASET:
  TYPE: 'glint360k'  # 'folder'
  TRAIN: '/sdata/datasets/glint360k'
  VAL: '/sdata/datasets/glint360k'
  VAL_TARGETS: ['lfw', 'cfp_fp', "agedb_30"]
  TEST: ''
  IMG_SIZE: 112
  NUM_IMAGES: 17091657
  TRANSFORM:
    RandomResizedCrop: 0.5
    HorizontalFlip: 0.5
    RandomBrightnessContrast: 0.0

SOLVER:
  OPTIM: 'sgd'
  BATCH_SIZE_PER_GPU: 64
  BASE_LR: 0.4
  WARMUP_EPOCH: 2
  NUM_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  LR_SCHEDULER_NAME: 'cosine'
  FP16: False
  LOGGER_STEP: 10
  VAL_STEP: 100
OUTPUT: 'runs'
NUM_WORKERS: 8
