MODEL:
  BACKBONE: 'cspresnet50'
  LOSS: 'circleloss'
  EMBEDDING_DIM: 512
  NUM_CLASS: 360232

DATASET:
  TYPE: 'folder'  # 'folder'
  TRAIN: '/dataset/dataset/face_test/'
  VAL: ''
  TEST: ''
  IMG_SIZE: 112

SOLVER:
  OPTIM: 'sgd'
  BATCH_SIZE: 32
  BASE_LR: 0.1
  WARMUP_EPOCH: 2
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: 'cosine'
  FP16: True
